### ISSUE TITLE
use another pin

### ISSUE THREAD

**Issue by otrab** [jonlidgard/rfsend#1]
Hi!, thanks for this great tool :)

It's posible to change the pin p8.11 ?? I have a beaglebone green wiresless and this pin it's for WIFI.
https://groups.google.com/d/msg/beagleboard/CwaqxPBKwEI/n6rLsYLXBwAJ

How can I do this?

regards,
Sebastián

**Comment by otrab** [comment]
I would like to use pin P9.27. 
The pins it's in pru mode 

> debian@beaglebone:~/rfsend$ config-pin -q p9.27
> P9_27 Mode: pruout

Acording to this doc, P9.27 is pr1_pru0_pru_r30_5 or pr1_pru0_pru_r31_5
http://exploringbeaglebone.com/wp-content/uploads/resources/BBBP9Header.pdf

So I made changes in rfsendpru.p but it does not work. (for testing I'm using arduino with rx 433 module)

```
SendHighLowPulse:
  SET r30, r30, 5 ; set 
HighPulseDelay1:
  SUB r9, r9, 1
  QBNE HighPulseDelay1, r9, 0
  CLR r30, r30, 5 ; clear 
LowPulseDelay1:
  SUB r10, r10, 1
  QBNE LowPulseDelay1, r10, 0
  RET

SendLowHighPulse:
  CLR r30, r30, 5 ; clear
LowPulseDelay2:
  SUB r9, r9, 1
  QBNE LowPulseDelay2, r9, 0
  SET r30, r30, 5 ; set 
HighPulseDelay2:
  SUB r10, r10, 1
  QBNE HighPulseDelay2, r10, 0
  RET
```

thanks for any help

Sebastián

**Comment by jonlidgard** [comment]
Hi I’m away till next Thursday, I’ll have a look at it when I get back.

Regards
Jon

**Comment by otrab** [comment]
Thanks!

**Comment by otrab** [comment]
Hi Jon,

Maybe the issue is here:
https://github.com/jonlidgard/rfsend/blob/40aace8d9b23d46bb77a2a415d897bbecb771397/rfsend.c#L201

after added some printf, in my beaglebone, the code exit. 

For some reason prussdrv_open(PRU_EVTOUT_0) exit the program

regards
Sebastián

**Comment by jonlidgard** [comment]
Are you running as root? You can only open the pruss driver with root privileges.

Regards
Jon

**Comment by otrab** [comment]
Yes, I'm trying with root

I try another simple example of PRU and fail in the same part.

My PRU is load, and I can use config-pin but the c program fail in
prussdrv_open

My kernel is 4.4.113-ti-r145

**Comment by jonlidgard** [comment]
Try my gist here:
https://gist.github.com/jonlidgard/1d9e0e92b4f219f3f40edfed260b851e

See if you can get the blink program to run.
Possible issue is you need Mode 5 for P9-27 whereas P8-11 uses mode 6 - could be a clash with EMC you may need to disable in the cape.
Apologies, I’m a bit rusty on the PRU stuff, I haven’t looked at it for a while.

Jon

**Comment by otrab** [comment]
It's working :)
thanks for this great guide

Now I'm have an issue with the 433TX antena, the comunication it's really bad

only for testing I put a wire between beaglebone and my arduino with the 433RX firmware and rfsend work perfect, but ussing the real 433TX and 433RX after 10 attempts to send codes only 1 worked

**Comment by jonlidgard** [comment]
Glad it works, I think the receiver may be the issue. When I use the transmitter with those sockets in the article I get great range all around the house. I’ve heard of others having issues with the receiver, you may need to upgrade to a decent Superhet type.

Jon

**Comment by otrab** [comment]
ok, thanks!
